# -*- coding: utf-8 -*-
"""visualization_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEnSsyrntGSsWWCh_bBT_3RpVZDadF47

###Question 2 - Principles of Data Science CS5530
Morgan Sansone
"""

import pandas as pd
import numpy as np
import requests
import io
import matplotlib.pyplot as plt
import seaborn as sns

"""##Ingest"""

# load data

# create dataframe
df_students = pd.read_csv('StudentsPerformance.csv')

print(df_students.head(5)) # print the first 5 values in the dataframe

"""##Preprocessing"""

# handle the missing values
print(df_students.isna().sum())
df_students.fillna(df_students.mean(numeric_only=True), inplace=True) # replace numerical NaN with mean

# create overall_avg column for V3
df_students['overall_avg'] = df_students[['math score', 'reading score', 'writing score']].mean(axis=1)

# save cleansed data
df_students.to_csv('cleansed_performance.csv', index=False)

"""##Analysis"""

# V1 - Are there gender differences in math vs reading?
plt.figure(figsize=(8, 6), dpi=300) # 800 x 6000 w dpi of 300

gender_mathvread_df = pd.melt(df_students, id_vars=['gender'], value_vars=['math score', 'reading score'], var_name='Subject', value_name='Score')
sns.boxplot(x='Subject', y='Score', hue='gender', data=gender_mathvread_df)
plt.title('Gender Differences in Math vs Reading Scores')
plt.xlabel('Subject')
plt.ylabel('Score')
plt.savefig('v1_gender_boxplot.png')
plt.show()

# V2 - Do students who completed test prep score higher in math?
plt.figure(figsize=(8, 6), dpi=300) # 800 x 6000 w dpi of 300

test_prep_avg = df_students.groupby('test preparation course')['math score'].mean()
avgmathscore_chart = test_prep_avg.plot.bar(figsize=(8, 6), color=['skyblue', 'salmon'], rot=0)

# scale & labels
plt.ylim(60, 72) # range of 60-72
plt.yticks(np.arange(60, 73, 2)) # tick every 2

plt.title('Average Math Score by Test Prep')
plt.xlabel('Test Prep Course')
plt.ylabel('Average Math Score')
plt.savefig('v2_test_prep_impact.png', dpi=300)
plt.show()

# V3 - Does lunch type (standard vs free/reduced) relate to outcomes?
plt.figure(figsize=(8, 6), dpi=300) # 800 x 6000 w dpi of 300

# avg for all 3 subjects
df_students['overall_avg'] = df_students[['math score', 'reading score', 'writing score']].mean(axis=1)

lunch_comparison = df_students.groupby('lunch')[['math score', 'reading score', 'writing score', 'overall_avg']].mean()
overall_avg_chart = lunch_comparison.plot.bar(figsize=(8, 6), rot=0)

# scale & labels
plt.ylim(55, 75) # range of 50-80
plt.yticks(np.arange(55, 76, 2)) # tick every 5

plt.title('Overall Test Performance by Lunch Type')
plt.xlabel('Lunch Type')
plt.ylabel('Average Overall Test Score')
plt.legend(title='Subject/Average', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.savefig('v3_lunch_type_bar.png', dpi=300, bbox_inches='tight')
plt.show()

# V4 - How strongly do the three subjects move together?
plt.figure(figsize=(8, 6), dpi=300) # 800 x 6000 w dpi of 300

# avg for all 3 subjects
correlation_matrix = df_students[['math score', 'reading score', 'writing score']].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")

plt.title('Coorelation Heatmap: Math, Reading and Writing Scores')
plt.savefig('v4_subject_correlation.png', dpi=300)
plt.show()

# V5 - How strongly are math and reading scores associated, and do students who
# completed the test‑preparation course have a different slope in the math–reading
# relationship than those who did not?

plt.figure(figsize=(8, 6), dpi=300) # 800 x 6000 w dpi of 300

sns.lmplot(x='reading score', y='math score', hue='test preparation course',
           data=df_students, height=6, aspect=1.33, # height=6 & aspect=1.33 results in ~8x6 inches
           scatter_kws={'alpha':0.5}, ci=None)

plt.title('Math vs. Reading Scores with Trend Lines by Test Prep')
plt.xlabel('Reading Score')
plt.ylabel('Math Score')

plt.savefig('v5_math_reading_scatter.png', dpi=300)
plt.show()